### ISSUE TITLE
Why there is "bukkitEntity" ?

### ISSUE THREAD

**Issue by j3zh1** [CentrumGuy/PlayerSimulator#1]
_PlayerSimulator/PlayerSimulator/src/com/CentrumGuy/PlayerSimulator/NMSUtils/DummyEntityPlayer.java_
line17,18,21 
why there is "bukkitEntity" when only nms is imported.
Thanks.

**Comment by CentrumGuy** [comment]
It's been a while since I coded this but I believe that a CraftPlayer is the CraftBukkit wrapper class for Minecraft's EntityPlayer class. After having the EntityPlayer, I converted it to a CraftPlayer to make use of CraftBukkit's handy methods for dealing with Minecraft players. It lets you use all the methods that come with Bukkit's "Player" class.
